export const villagerData = [{"firstName":"Bethany","lastName":"Stoker","personalityTraits":["Friendly","Outgoing","Confident"],"age":36,"disposition":"Optimistic","profession":"Farmer","skills":[{"skill":"Planting and growing crops","level":100},{"skill":"Harvesting crops","level":100},{"skill":"Caring for animals","level":80},{"skill":"Cooking","level":50}]},{"firstName":"Gregory","lastName":"Moore","personalityTraits":["Cautious","Analytical","Reserved"],"age":45,"disposition":"Cautious","profession":"Hunter","skills":[{"skill":"Tracking","level":75},{"skill":"Archery","level":80},{"skill":"Trapping","level":70},{"skill":"Fishing","level":60}]},{"firstName":"William","lastName":"Glover","personalityTraits":["Cheerful","Creative","Passionate"],"age":30,"disposition":"Adventurous","profession":"Blacksmith","skills":[{"skill":"Metalworking","level":90},{"skill":"Toolmaking","level":80},{"skill":"Leatherworking","level":70},{"skill":"Woodworking","level":70}]},{"firstName":"Sofia","lastName":"Johnson","personalityTraits":["Kind","Thoughtful","Wise"],"age":41,"disposition":"Practical","profession":"Healer","skills":[{"skill":"Herbalism","level":90},{"skill":"Healing remedies","level":85},{"skill":"Caring for the sick","level":80},{"skill":"First aid","level":70}]},{"firstName":"Luke","lastName":"Anderson","personalityTraits":["Logical","Detail-oriented","Driven"],"age":52,"disposition":"Stoic","profession":"Carpenter","skills":[{"skill":"Carpentry","level":95},{"skill":"Construction","level":85},{"skill":"Woodworking","level":75},{"skill":"Masonry","level":70}]},{"firstName":"Lena","lastName":"Hills","personalityTraits":["Calm","Patient","Observant"],"age":53,"disposition":"Compassionate","profession":"Midwife","skills":[{"skill":"Childbirth","level":95},{"skill":"Herbal remedies for labor","level":85},{"skill":"Breastfeeding","level":75},{"skill":"Healing","level":70}]},{"firstName":"Emily","lastName":"Wilson","personalityTraits":["Spirited","Independent","Strong-willed"],"age":32,"disposition":"Daring","profession":"Tanner","skills":[{"skill":"Curing leather","level":90},{"skill":"Stitching leather","level":80},{"skill":"Dying leather","level":70},{"skill":"Tanning hides","level":70}]},{"firstName":"Owen","lastName":"Roberts","personalityTraits":["Honest","Reliable","Supportive"],"age":48,"disposition":"Honest","profession":"Fisherman","skills":[{"skill":"Fishing","level":90},{"skill":"Net making","level":80},{"skill":"Boat maintenance","level":70},{"skill":"Navigation","level":70}]},{"firstName":"Josephine","lastName":"Taylor","personalityTraits":["Caring","Empathetic","Generous"],"age":29,"disposition":"Loyal","profession":"Weaver","skills":[{"skill":"Weaving","level":95},{"skill":"Dyeing fabrics","level":85},{"skill":"Spinning wool","level":75},{"skill":"Sewing","level":70}]},{"firstName":"Alexander","lastName":"White","personalityTraits":["Adaptable","Resourceful","Pragmatic"],"age":54,"disposition":"Self-motivated","profession":"Butcher","skills":[{"skill":"Curing meats","level":90},{"skill":"Salting meats","level":80},{"skill":"Smoking meats","level":70},{"skill":"Cooking","level":70}]},{"firstName":"Catherine","lastName":"Adams","personalityTraits":["Curious","Imaginative","Passionate"],"age":24,"disposition":"Determined","profession":"Herbalist","skills":[{"skill":"Identifying herbs","level":90},{"skill":"Harvesting herbs","level":80},{"skill":"Preserving herbs","level":70},{"skill":"Preparing medicines","level":70}]},{"firstName":"Noah","lastName":"Brown","personalityTraits":["Understanding","Creative","Adaptable"],"age":37,"disposition":"Caring","profession":"Woodcutter","skills":[{"skill":"Chopping wood","level":90},{"skill":"Axe sharpening","level":80},{"skill":"Carving wood","level":70},{"skill":"Firewood collection","level":70}]},{"firstName":"Ava","lastName":"Miller","personalityTraits":["Adventurous","Optimistic","Determined"],"age":43,"disposition":"Adventurous","profession":"Baker","skills":[{"skill":"Baking bread","level":90},{"skill":"Making pastries","level":80},{"skill":"Decorating cakes","level":70},{"skill":"Making jams","level":70}]},{"firstName":"Isaac","lastName":"Jones","personalityTraits":["Hardworking","Determined","Organized"],"age":51,"disposition":"Practical","profession":"Beekeeper","skills":[{"skill":"Harvesting honey","level":90},{"skill":"Making wax candles","level":80},{"skill":"Pollinating crops","level":70},{"skill":"Making mead","level":70}]},{"firstName":"Mia","lastName":"Taylor","personalityTraits":["Inventive","Analytical","Resourceful"],"age":31,"disposition":"Resourceful","profession":"Brewer","skills":[{"skill":"Brewing beer","level":90},{"skill":"Making cider","level":80},{"skill":"Distilling spirits","level":70},{"skill":"Distilling wine","level":70}]},{"firstName":"Sophie","lastName":"Wilson","personalityTraits":["Curious","Imaginative","Creative"],"age":11,"disposition":"Adventurous","profession":"Student","skills":[{"skill":"Reading","level":50},{"skill":"Exploring","level":40},{"skill":"Drawing","level":30},{"skill":"Playing","level":20}]},{"firstName":"Jacob","lastName":"Miller","personalityTraits":["Energetic","Brave","Outgoing"],"age":13,"disposition":"Confident","profession":"Student","skills":[{"skill":"Reading","level":50},{"skill":"Exploring","level":40},{"skill":"Sports","level":30},{"skill":"Playing","level":20}]},{"firstName":"Emma","lastName":"Adams","personalityTraits":["Smart","Independent","Resilient"],"age":8,"disposition":"Inquisitive","profession":"Student","skills":[{"skill":"Reading","level":50},{"skill":"Exploring","level":40},{"skill":"Writing","level":30},{"skill":"Playing","level":20}]},{"firstName":"Liam","lastName":"Roberts","personalityTraits":["Cheerful","Creative","Passionate"],"age":10,"disposition":"Bold","profession":"Student","skills":[{"skill":"Reading","level":50},{"skill":"Exploring","level":40},{"skill":"Singing","level":30},{"skill":"Playing","level":20}]},{"firstName":"Olivia","lastName":"Jones","personalityTraits":["Thoughtful","Kind","Friendly"],"age":12,"disposition":"Caring","profession":"Student","skills":[{"skill":"Reading","level":50},{"skill":"Exploring","level":40},{"skill":"Painting","level":30},{"skill":"Playing","level":20}]}];

export const skills = {
    "Planting and growing crops": {},
    "Harvesting crops": {},
    "Caring for animals": {},
    "Cooking": {},
    "Tracking": {},
    "Archery": {},
    "Trapping": {},
    "Fishing": {},
    "Metalworking": {},
    "Toolmaking": {},
    "Leatherworking": {},
    "Woodworking": {},
    "Herbalism": {},
    "Healing remedies": {},
    "Caring for the sick": {},
    "First aid": {},
    "Carpentry": {},
    "Construction": {},
    "Masonry": {},
    "Childbirth": {},
    "Herbal remedies for labor": {},
    "Breastfeeding": {},
    "Healing": {},
    "Curing leather": {},
    "Stitching leather": {},
    "Dying leather": {},
    "Tanning hides": {},
    "Net making": {},
    "Boat maintenance": {},
    "Navigation": {},
    "Weaving": {},
    "Dyeing fabrics": {},
    "Spinning wool": {},
    "Sewing": {},
    "Curing meats": {},
    "Salting meats": {},
    "Smoking meats": {},
    "Identifying herbs": {},
    "Harvesting herbs": {},
    "Preserving herbs": {},
    "Preparing medicines": {},
    "Chopping wood": {},
    "Axe sharpening": {},
    "Carving wood": {},
    "Firewood collection": {},
    "Baking bread": {},
    "Making pastries": {},
    "Decorating cakes": {},
    "Making jams": {},
    "Harvesting honey": {},
    "Making wax candles": {},
    "Pollinating crops": {},
    "Making mead": {},
    "Brewing beer": {},
    "Making cider": {},
    "Distilling spirits": {},
    "Distilling wine": {},
    "Reading": {},
    "Exploring": {},
    "Drawing": {},
    "Playing": {},
    "Sports": {},
    "Writing": {},
    "Singing": {},
    "Painting": {}
}

export const dispositions = {
    "Optimistic": {},
    "Cautious": {},
    "Adventurous": {},
    "Practical": {},
    "Stoic": {},
    "Compassionate": {},
    "Daring": {},
    "Honest": {},
    "Loyal": {},
    "Self-motivated": {},
    "Determined": {},
    "Caring": {},
    "Resourceful": {},
    "Confident": {},
    "Inquisitive": {},
    "Bold": {}
};

export const personalityTraits = {
    "Friendly": {},
    "Outgoing": {},
    "Confident": {},
    "Cautious": {},
    "Analytical": {},
    "Reserved": {},
    "Cheerful": {},
    "Creative": {},
    "Passionate": {},
    "Kind": {},
    "Thoughtful": {},
    "Wise": {},
    "Logical": {},
    "Detail-oriented": {},
    "Driven": {},
    "Calm": {},
    "Patient": {},
    "Observant": {},
    "Spirited": {},
    "Independent": {},
    "Strong-willed": {},
    "Honest": {},
    "Reliable": {},
    "Supportive": {},
    "Caring": {},
    "Empathetic": {},
    "Generous": {},
    "Adaptable": {},
    "Resourceful": {},
    "Pragmatic": {},
    "Curious": {},
    "Imaginative": {},
    "Understanding": {},
    "Adventurous": {},
    "Optimistic": {},
    "Determined": {},
    "Hardworking": {},
    "Organized": {},
    "Inventive": {},
    "Energetic": {},
    "Brave": {},
    "Smart": {},
    "Resilient": {}
};
